<?php
/**********************************************
This file pulls the css from the database
Styles are generated by the options/css-build.php file
***********************************************/
	if(!headers_sent() & !is_admin()) {
		header('Content-type: text/css');   
		header("Cache-Control: must-revalidate"); 
		$offset = 72000 ; 
		$ExpStr = 'Expires: ' . gmdate("D, d M Y H:i:s", time() + $offset) . ' GMT'; 
		header($ExpStr);
	}
echo get_option('tech_styles');
?>