<?php
//This file holds the options array for use in the controlpanel.php and theme-init.php files.
$options = array (
	array(	"name" => "Layout",
              	"type" => "header",
              	"selected" => "selected",
              	"position" => "1",
              	"tab_id" => "layout",
              	"anchor" =>"general"),

    	array(	"name" => "Number of Columns",
            	"id" => "column",
				"old_id" => "techcolumn",
            	"type" => "radio",
            	"std" => "3",
            	"java" => "onchange=\"pagewidth(this.form)\"",
            	"options" => array("3", "2", "1")),

		array(	"name" => "Three Column Content Layout",
            	"image" => "images/layout.jpg",
				"old_id" => "tech_sidebar_pos",
            	"id" => "sidebar_pos",
            	"type" => "select",
            	"std" => "Sidebar - Content - Sidebar",
            	"options" => array("Sidebar - Content - Sidebar", "Content - Sidebar - Sidebar")),
	
		array(	"name" => "Fixed or Fluid Width",		
            	"id" => "page_type",
		"old_id" => "tech_page_type",
            	"std" => "Fluid Width",
            	"type" => "radio",
            	"java" => "onchange=\"pagewidth(this.form)\"",
            	"options" => array("Fixed Width", "Fluid Width")),

		array(	"name" => "Page Width <br /><small>Fluid Width - Percentage of Total Screen Size <br />Fixed Width - Width in number of pixels</small>",
            	"id" => "page_width",
		"old_id" => "tech_page_width",
		"string" => "num",				
            	"std" => "0",
            	"size" => "3",
            	"java" => "onchange=\"pagewidth(this.form)\"",
            	"text" => "<span id=\"page_width_sign\"></span>",
            	"tooltip" => "<br /><small><span id=\"page_width_error\"></span></small>",
            	"type" => "text"),

		array(	"name" => "Main Column <small>(Post Content)</small> Width - Percentage of Page Width",
            	"id" => "main_column_width",
		"old_id" => "tech_main_column_width",
		"string" => "num",				
            	"std" => "0",
            	"size" => "3",
            	"java" => "onchange=\"pagewidth(this.form)\"",
            	"text" => "%",
            	"type" => "text"),

		array( 	"name" => "Sidebar<span id=\"sidebar_s\">s</span> Width - Percentage of Page Width",
            	"id" => "sidebar_width",
		"old_id" => "tech_sidebar_width",
		"string" => "num",				
            	"std" => "0",
            	"size" => "3",
            	"java" => "onchange=\"pagewidth(this.form)\"",
            	"text" => "%",
            	"type" => "text"),
	
		array(	"name" => "Total Content Width - <br /> <small> If Javascript is disabled this field will not update</small>",
            	"id" => "total",
				"old_id" => "tech_total",
            	"std" => "",
            	"size" => "3",
            	"java" => "readonly = \"readonly\" ",
            	"tooltip" => "<br /><small><span id=\"totalerror\"></span></small>",
            	"text" => "%",
            	"type" => "text"),
				
		array(	"name" => "Fav Icon Image<br /><small>Fav Icon must be an .ico file<br/>Browse for a new image or chose previously uploaded image</small>",		
            	"id" => "favicon_image",
				"old_id" => "unused before 1.8.7",
				"std" => "",
				"reset" => "favicon_image_reset",
				"select" => "favicon_image_select",
            	"type" => "upload"),

    	array(  "name" => "Display Sidebars on Blog Home Page",
            	"id" => "home_sidebar",
				"old_id" => "unused since 1.8.7",
            	"type" => "radio",
            	"std" => "Yes",
            	"options" => array("Yes", "No")),				
				
    	array(  "name" => "Display Sidebars on Single Post Pages",
            	"id" => "single_sidebar",
				"old_id" => "tech_single_sidebar",
            	"type" => "radio",
            	"std" => "No",
            	"options" => array("Yes", "No")),

    	array(  "name" => "SEO Features<a href=\"javascript:tabchange(6)\">*(see notes)</a><br /><small>Disable this if any SEO plugins are used</small>",
            	"id" => "seo",
				"old_id" => "techseo",
            	"type" => "radio",
            	"std" => "On",
            	"options" => array("On", "Off")),
				
    	array(  "name" => "Thickbox on Images<br /><small>Use Thickbox to automatically overlay images on pages</small>",
            	"id" => "thickbox",
				"old_id" => "tech_thickbox",
            	"type" => "radio",
            	"std" => "Off",
            	"options" => array("On", "Off")),

    	array(	"name" => "Display Blog Title and Tagline in header<br /><small>Set to no if your custom header image already has your blog title and tagline</small>",
            	"id" => "blog_title",
				"old_id" => "tech_blog_title",
            	"type" => "radio",
            	"std" => "Yes",
            	"options" => array("Yes", "No")),

    	array(	"name" => "Blog Title and Tagline Horizontal Alignment",
				"id" => "blog_title_align",
				"old_id" => "tech_blog_title_align",
            	"type" => "radio",
            	"std" => "Left",
            	"options" => array("Left", "Center" , "Right")),

    	array( 	"name" => "Single Page Header Title Text<br /><small>Show the Post title as the main heading and the the Blog title as the tagline on single pages.<br />  Always Blog Title will only display the Blog Title and Tagline set in the General Options of the Blog.</small>",
            	"id" => "blog_title_text",
				"old_id" => "tech_blog_title_text",
            	"type" => "radio",
            	"std" => "Single Post Title",
            	"options" => array("Single Post Title", "Always Blog Title")),

    	array(	"name" => "Static CSS<br /><small>For Advanced Users who would like to edit the style.css file directly.<br />Setting this to static will stop using the Dynamic style.php in favor of the static style.css<br /> If you would like the changes you've made already to transfer then below <br />is the CSS being used currently and allow you to copy and paste to the style.css file.",
		"id" => "static_css",
		"old_id" => "unused before 1.8.4",
            	"type" => "radio",
            	"std" => "Dynamic",
		"display" => "style",
            	"options" => array("Static", "Dynamic")),
				
    	array(	"name" => "Custom CSS <br /><small><strong>No HTML allowed</strong><br />Here you can enter your own CSS. <br />Please keep in mind proper CSS structure.</small>",
            	"id" => "custom_styles",
		"old_id" => "tech_custom_styles",
		"string" => "nohtml",
            	"std" => "",
		"display" => "style",
            	"type" => "textarea"),
				
    	array( 	"name" => "Navigation",
		"type" => "header",
              	"tab_id" => "nav",
             	"anchor" => "nav"),
				
    	array(	"name" => "Navigation Menu Type<br /><small>Standard - Pages listed in horizontal menu in a single tier<br />Two Tier - Parent pages listed in horizontal menu with any sub-pages listed in lower menu<br />Disable the horizontal menu and visit the <a href=\"widgets.php\">widgets</a> page to add<br /> the Techozoic Sidebar Navigation widget</small>",
            	"id" => "nav_menu_type",
				"old_id" => "tech_nav_menu_type",
            	"type" => "select",
            	"std" => "Standard",
            	"options" => array("Standard", "Two Tier", "Dropdown", /*"WP 3 Menu",*/ "Disable")),

				array(	"name" => "Navigation Menu Alignment",
            	"id" => "nav_align",
				"old_id" => "unused before 1.8.7",
            	"type" => "radio",
            	"std" => "Left",
            	"options" => array("Left","Center")),

		array(	"name" => "Navigation Button Width <br /><small>Set to <strong>0</strong> for variable sized buttons <br />- Dropdown Menu must have variable sized buttons to work</small>",
            	"id" => "nav_button_width",
				"old_id" => "tech_nav_button_width",
				"string" => "num",
            	"std" => "0",
            	"size" => "2",
            	"text" => "em",
            	"type" => "text"),

		array(	"name" => "Navigation Menu Exclusion<small><br /><strong>Choose which pages to exclude from all Navigation Menus.<br />Hold CTRL to select multiple pages.</small>",
            	"id" => "nav_exclude_list",
				"old_id" => "unused before 1.8.4",
            	"std" => "",
				"list" => "pages",
				"type" => "wp_list"),

    	array(	"name" => "Log In/Out Links<br /><small>Enable Dashboard and Log in/out links.</small>",
            	"id" => "dashboard_link",
				"old_id" => "unused before 1.8.4",
            	"type" => "radio",
            	"std" => "On",
            	"options" => array("On","Off")),				
				
    	array(	"name" => "Breadcrumbs<br /><small>Enable Breadcrumb navigation.  Useful with Sidebar Nav Widget.</small>",
            	"id" => "breadcrumbs",
				"old_id" => "unused before 1.8.4",
            	"type" => "radio",
            	"std" => "Off",
            	"options" => array("On","Off")),
				
    	array(	"name" => "Display Home Link<br /><small>Display the link back to the Blog Home</small>",
            	"id" => "nav_home_link",
				"old_id" => "unused before 1.8.4",
            	"type" => "radio",
            	"std" => "Yes",
            	"options" => array("Yes","No")),
				
		array(	"name" => "Text for Home Link<small></a> <br />Text displayed for the link to the blog home</small>",
            	"id" => "nav_home_text",
				"old_id" => "unused before 1.8.4",
            	"std" => "Home",
            	"size" => "25",
            	"type" => "text"),
				
    	array(	"name" => "Display Custom Links<br /><small>Before or After default links</small>",
            	"id" => "nav_cust_link_display",
				"old_id" => "unused before 1.8.4",
            	"type" => "radio",
            	"std" => "Before",
            	"options" => array("Before","After")),
				
		array(	"name" => "Custom Navigation Link<br /><small>Link should be entered in this form<br /> <strong>Link Name|http://www.link.com</strong></small> <br /><input type=\"button\" value=\"Add Link\" onclick=\"addlink(2);\" class=\"aligncenter\" />",
            	"id" => "nav_link_1",
				"old_id" => "unused before 1.8.4",
				"before" => "</table><h3> Custom Navigation Links</h3><div id=\"nav_link_div_1\"><table class=\"optiontable\">",
				"after" => "</table></div><table class=\"optiontable\">",
				"string" => "nav_link",
            	"std" => "",
            	"size" => "50",
            	"type" => "text"),
				
		array(	"name" => "Custom Navigation Link<br /><small>Link should be entered in this form<br /> <strong>Link Name|http://www.link.com</strong></small> <br /><input type=\"button\" value=\"Add Link\" onclick=\"addlink(3);\" class=\"aligncenter\" /> <input type=\"button\" value=\"Remove Link\" onclick=\"dellink(2);\" class=\"aligncenter\" />",
            	"id" => "nav_link_2",
				"old_id" => "unused before 1.8.4",
				"before" => "</table><div id=\"nav_link_div_2\"><table class=\"optiontable\">",
				"after" => "</table></div><table class=\"optiontable\">",
				"string" => "nav_link",
            	"std" => "",
            	"size" => "50",
            	"type" => "text"),
				
		array(	"name" => "Custom Navigation Link<br /><small>Link should be entered in this form<br /> <strong>Link Name|http://www.link.com</strong></small> <br /><input type=\"button\" value=\"Add Link\" onclick=\"addlink(4);\" class=\"aligncenter\" /> <input type=\"button\" value=\"Remove Link\" onclick=\"dellink(3);\" class=\"aligncenter\" />",
            	"id" => "nav_link_3",
				"old_id" => "unused before 1.8.4",
				"before" => "</table><div id=\"nav_link_div_3\"><table class=\"optiontable\">",
				"after" => "</table></div><table class=\"optiontable\">",
				"string" => "nav_link",
            	"std" => "",
            	"size" => "50",
            	"type" => "text"),
				
		array(	"name" => "Custom Navigation Link<br /><small>Link should be entered in this form<br /> <strong>Link Name|http://www.link.com</strong></small> <br /><input type=\"button\" value=\"Add Link\" onclick=\"addlink(5);\" class=\"aligncenter\" /> <input type=\"button\" value=\"Remove Link\" onclick=\"dellink(4);\" class=\"aligncenter\" />",
            	"id" => "nav_link_4",
				"old_id" => "unused before 1.8.4",
				"before" => "</table><div id=\"nav_link_div_4\"><table class=\"optiontable\">",
				"after" => "</table></div><table class=\"optiontable\">",
				"string" => "nav_link",
            	"std" => "",
            	"size" => "50",
            	"type" => "text"),
				
		array(	"name" => "Custom Navigation Link <br />- Limit of 5<br /><small>Link should be entered in this form<br /> <strong>Link Name|http://www.link.com</strong></small> <br /><input type=\"button\" value=\"Remove Link\" onclick=\"dellink(5);\" class=\"aligncenter\" />",
            	"id" => "nav_link_5",
				"old_id" => "unused before 1.8.4",
				"before" => "</table><div id=\"nav_link_div_5\"><table class=\"optiontable\">",
				"after" => "</table></div><table class=\"optiontable\">",
				"string" => "nav_link",
            	"std" => "",
            	"size" => "50",
            	"type" => "text"),
		
    	array( 	"name" => "Typography",
				"type" => "header",
              	"tab_id" => "font",
             	"anchor" => "font"),
	 
		array(	"name" => "Base Font Size <br />-<small>-Default text size<br />--Text won't update size if Javascript is disabled</small>",
            	"id" => "body_font_size",
				"old_id" => "tech_body_font_size",
				"string" => "num",
            	"std" => "10",
            	"size" => "2",
            	"text" => "px <input type=\"button\" value=\"Show Text Size\" onchange=\"textsize(this.form);\" style=\"margin-left:10px\" />",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"type" => "text"),

		array("name" => "<span id =\"main_heading_font_size_out\"><span id =\"main_heading_font_size\" style=\"font-size:3em;line-height:1em\">Main Heading Font</span></span>",
            	"id" => "main_heading_font_size",
				"old_id" => "tech_main_heading_font_size",
				"string" => "num",
            	"std" => "3.0",
            	"size" => "2",
            	"text" => "em",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"type" => "text"),

		array("name" => "<span id =\"post_heading_font_size_out\"><span id =\"post_heading_font_size\" style=\"font-size:2em;line-height:1em\">Post Heading Font</span></span>",
            	"id" => "post_heading_font_size",
				"old_id" => "tech_post_heading_font_size",
				"string" => "num",
            	"std" => "2.0",
            	"size" => "2",
            	"text" => "em",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"type" => "text"),
				
		array("name" => "<span id =\"side_heading_font_size_out\"><span id =\"side_heading_font_size\" style=\"font-size:1.6em;line-height:1em\">Sidebar Heading Font</span></span>",
            	"id" => "side_heading_font_size",
				"old_id" => "tech_side_heading_font_size",
				"string" => "num",
            	"std" => "1.6",
            	"size" => "2",
            	"text" => "em",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"type" => "text"),

		array("name" => "<span id =\"post_text_font_size_out\" ><span id =\"post_text_font_size\" style=\"font-size:2em;line-height:1em\">Post Text Font</span></span>",
            	"id" => "post_text_font_size",
				"old_id" => "tech_post_text_font_size",
				"string" => "num",
            	"std" => "1.0",
            	"size" => "2",
            	"text" => "em",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"type" => "text"),

		array("name" => "<span id =\"small_font_size_out\"><span id =\"small_font_size\" style=\"font-size:.9em;line-height:1em\">Metadata Font</span></span>",
            	"id" => "small_font_size",
				"old_id" => "tech_small_font_size",
				"string" => "num",
            	"std" => ".9",
            	"size" => "2",
            	"text" => "em",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"type" => "text"),

		array(	"name" => "Header Font<br /><div class=\"fonts\"><span class=\"trebuchet\">Trebuchet</span> | <span class=\"verdana\">Verdana</span> | <span class=\"georgia\">Georgia</span> | <span class=\"tahoma\">Tahoma</span> <br /> <span class=\"arial\">Arial</span> | <span class=\"times\">Times New Roman</span> | <span class=\"lucida\">Lucida Sans Unicode</span></div> | <span class=\"impact\">Impact</span></div>",
            	"id" => "header_font",
				"old_id" => "tech_header_font",
            	"type" => "select",
            	"std" => "Verdana",
            	"java" => "onchange=\"textsize(this.form);\"",
            	"options" => array("Trebuchet MS", "Verdana", "Georgia", "Tahoma", "Arial", "Times New Roman","Lucida Sans Unicode","Impact")),

		array(	"name" => "Post Body Font<br /><div class=\"fonts\"><span class=\"trebuchet\">Trebuchet</span> | <span class=\"verdana\">Verdana</span> | <span class=\"georgia\">Georgia</span> | <span class=\"tahoma\">Tahoma</span> <br /> <span class=\"arial\">Arial</span> | <span class=\"times\">Times New Roman</span> | <span class=\"lucida\">Lucida Sans Unicode</span></div> | <span class=\"impact\">Impact</span>",
            	"id" => "body_font",
				"old_id" => "tech_body_font",
            	"type" => "select",
            	"std" => "Lucida Sans Unicode",
				"java" => "onchange=\"textsize(this.form);\"",
            	"options" => array("Trebuchet MS", "Verdana", "Georgia", "Tahoma", "Arial", "Times New Roman","Lucida Sans Unicode","Impact")),

		array(	"name" => "Default Page Font<br /><div class=\"fonts\"><span class=\"trebuchet\">Trebuchet</span> | <span class=\"verdana\">Verdana</span> | <span class=\"georgia\">Georgia</span> | <span class=\"tahoma\">Tahoma</span> <br /> <span class=\"arial\">Arial</span> | <span class=\"times\">Times New Roman</span> | <span class=\"lucida\">Lucida Sans Unicode</span></div> | <span class=\"impact\">Impact</span>",
            	"id" => "default_font",
				"old_id" => "tech_default_font",
				"type" => "select",
            	"java" => "onchange=\"textsize(this.form);\"",				
            	"std" => "Lucida Sans Unicode",
            	"options" => array("Trebuchet MS", "Verdana", "Georgia", "Tahoma", "Arial", "Times New Roman","Lucida Sans Unicode","Impact")),
				
		array("name" => "Cufon Font Replacement<br /><small>Visit this <a href=\"http://cufon.shoqolate.com/generate/\">link</a> to find out about Cufon.</small>",
            	"id" => "cufon_font",
				"old_id" => "unused before 1.8.7",
            	"std" => "Disable",
            	"type" => "radio",
				"options" => array("Enable","Disable")),
				
		array("name" => "Cufon Font Replacement<br /><small>Check which headings you would like replaced.</small>",
            	"id" => "cufon_font_headings",
				"old_id" => "unused before 1.8.7",
            	"std" => "",
            	"type" => "checkbox",
				"options" => array("Main Blog Title","Sidebar Titles","Post Titles")),
				
		array("name" => "Cufon Font Replacement<br /><small>Choose the Font you would like to replace with.<br />More coming in later versions.</small>",
            	"id" => "cufon_font_list",
            	"image" => "images/font.jpg",
				"old_id" => "unused before 1.8.7",
            	"std" => "",
            	"type" => "select",
				"options" => array("contempory","journal","nevis")),

    	array(	"name" => "Custom Backgrounds",
				"type" => "header",
              	"tab_id" => "background",
				"anchor" =>"background"),				
				
		array(	"name" => "Page Background Image<br /><small>Use a tiled image for best results<br />Browse for a new image or chose previously uploaded image</small>",		
            	"id" => "bg_image",
				"old_id" => "unused before 1.8.5",
				"std" => "",
				"reset" => "bg_image_reset",
				"select" => "bg_image_select",
            	"type" => "upload"),
				
		array(	"name" => "Page Background Image Repeat<br /><small>X is Horizontal, Y is Vertical, both repeat tiled pattern</small>",
		"old_id" => "unused before 1.8.6",
            	"id" => "bg_image_repeat",
            	"type" => "checkbox",
            	"std" => "X,Y",
            	"options" => array("X","Y")),

		array(	"name" => "Content Background Image<br /><small>Use a tiled image for best results<br />Browse for a new image or chose previously uploaded image</small>",		
            	"id" => "content_bg_image",
				"old_id" => "unused before 1.8.7",
				"std" => "",
				"reset" => "content_bg_image_reset",
				"select" => "content_bg_image_select",
            	"type" => "upload"),
				
		array(	"name" => "Content Background Image Repeat<br /><small>X is Horizontal, Y is Vertical, both repeat tiled pattern</small>",
		"old_id" => "unused before 1.8.6",
            	"id" => "content_bg_image_repeat",
            	"type" => "checkbox",
            	"std" => "X,Y",
            	"options" => array("X","Y")),
				
				
    	array(	"name" => "Color Options",
				"type" => "header",
              	"tab_id" => "color",
				"anchor" =>"color"),

		array(	"name" => "Prebuilt Color Scheme<br /><small>Choose Custom 1 or 2 to specify your own scheme<br />Two Custom options are provided to save two custom color schemes</small>",
            	"id" => "color_scheme",
				"old_id" => "tech_color_scheme",
            	"type" => "select",
            	"java" => "onchange=\"colorhide(this.form)\"",
            	"std" => "Custom 1",
            	"after" => "</table><div id=\"loading\"><img src=\"" . get_bloginfo('template_directory') ."/images/ajax-loader.gif\" alt=\"loading\"/></div><table class=\"optiontable\">",
            	"options" => array("Custom 1","Custom 2", "Blue", "Khaki", "Red", "Grunge")),
			
    	array(	"name" => "Body Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_bg_color1",
				"old_id" => "tech_cust_bg_color1",
            	"std" => "#A0B3C2",
            	"java" => "class=\"color\"",
            	"size" => "8",
            	"before" => "</table><div id=\"custom_color\"><h3>Custom 1</h3><table class=\"optiontable\">",
            	"type" => "text"),

    	array(	"name" => "Content Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_content_bg_color1",
		"old_id" => "unused before 1.8.7",
            	"std" => "#F7F7F7",
            	"java" => "class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Accent Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_acc_color1",
				"old_id" => "tech_cust_acc_color1",
            	"std" => "#A0B3C2",
            	"java" => "class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array( 	"name" => "Text Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small> ",
            	"id" => "cust_text_color1",
				"old_id" => "tech_cust_text_color1",
            	"std" => "#2C4353",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Link Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small> ",
            	"id" => "cust_link_color1",
				"old_id" => "tech_cust_link_color1",
            	"std" => "#597EAA",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Link Hover Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_link_hov_color1",
				"old_id" => "tech_cust_link_hov_color1",
            	"std" => "#114477",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Nav Button Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_nav_bg_color1",
				"old_id" => "tech_cust_nav_bg_color1",
            	"std" => "#E3E3E3",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Post Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small> ",
            	"id" => "cust_post_bg_color1",
				"old_id" => "tech_cust_post_bg_color1",
            	"std" => "#E3E3E3",
            	"java" => " class=\"color\"",
            	"size" => "8",
				"after" => "</table><input type=\"button\" value=\"Reset Colors\" onclick=\"resetcolor();\" class=\"alignright\" /></div>",
            	"type" => "text"),

    	array(	"name" => "Body Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_bg_color2",
				"old_id" => "tech_cust_bg_color2",
            	"std" => "#A0B3C2",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"before" => "</table><div id=\"custom_color2\"><h3>Custom 2</h3><table class=\"optiontable\">",
            	"type" => "text"),

    	array(	"name" => "Content Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_content_bg_color2",
		"old_id" => "unused before 1.8.7",
            	"std" => "#F7F7F7",
            	"java" => "class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Accent Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_acc_color2",
				"old_id" => "tech_cust_acc_color2",
            	"std" => "#A0B3C2",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Text Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small> ",
            	"id" => "cust_text_color2",
				"old_id" => "tech_cust_text_color2",
				"std" => "#2C4353",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Link Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small> ",
            	"id" => "cust_link_color2",
				"old_id" => "tech_cust_link_color2",
            	"std" => "#597EAA",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Link Hover Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
				"id" => "cust_link_hov_color2",
				"old_id" => "tech_cust_link_hov_color2",
            	"std" => "#114477",
            	"java" => " class=\"color\"",
				"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Nav Button Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small>",
            	"id" => "cust_nav_bg_color2",
				"old_id" => "tech_cust_nav_bg_color2",
            	"std" => "#E3E3E3",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"type" => "text"),

    	array(	"name" => "Post Background Color<br /><small> Choose or Type a <a href=\"http://www.w3schools.com/HTML/html_colors.asp\" target=\"_blank\">HEX color code</a> </small> ",
            	"id" => "cust_post_bg_color2",
				"old_id" => "tech_cust_post_bg_color2",
            	"std" => "#E3E3E3",
            	"java" => " class=\"color\"",
            	"size" => "8",
            	"after" => "</table><input type=\"button\" value=\"Reset Colors\" onclick=\"resetcolor(2);\" class=\"alignright\" /></div>",
            	"type" => "text"),

		array(	"name" => "Ad Placement",
				"type" => "header",
             	"tab_id" => "tab4",
             	"anchor" =>"tab4"),			
			
    	array(	 "name" => "Home Page Ad Code<br /><small>This Ad Code will be displayed a total of 3 times.<br />Best ads are banner ads no wider than 500 pixels<br />*Only html and javascript accepted</small>",
            	"id" => "ad_code",
				"old_id" => "tech_ad_code",
            	"std" => "",
            	"type" => "textarea"),

    	array( 	"name" => "Number of Posts Between Ad Units",
            	"id" => "ad_int",
				"old_id" => "tech_ad_int",
            	"type" => "radio",
            	"std" => "3",
            	"options" => array("6", "5", "4", "3", "2", "1")),

    	array(	"name" => "Home Page Header Ad Code<br /><small>This Ad Code will be displayed on the home <br />page below the header and navigation.<br />Best ads are banner ads no wider than 500 pixels<br />*Only html and javascript accepted</small>",
            	"id" => "header_ad_code",
				"old_id" => "tech_header_ad_code",
				"std" => "",
            	"type" => "textarea"),

    	array(	"name" => "Single Post Ad Code<br /><small>This Ad Code will be displayed on the single post page.<br />Best ads are banner ads no wider than 500 pixels<br />*Only html and javascript accepted</small>",
            	"id" => "sing_ad_code",
				"old_id" => "tech_sing_ad_code",
            	"std" => "",
            	"type" => "textarea"),

    	array(	"name" => "Single Post Ad Position <br/><small>Above or below the post content on single page</small>",
            	"id" => "sing_ad_pos",
				"old_id" => "tech_sing_ad_pos",
				"type" => "radio",
            	"std" => "Above",
            	"options" => array("Above", "Below")),

		array( 	"name" => "Standard Header Settings",
				"type" => "header",
             	"tab_id" => "headerset",
             	"anchor" =>"headerset"),	

		array(	"name" => "Header Image<br /><small> <strong> Use the <a href=\"admin.php?page=techozoic_header_admin\">Header Image page</a> to upload custom headers and choose header image.</strong><br />If errors occur use dropdown menu <br />Select Rotate to rotate through all images <a href=\"javascript:tabchange(6)\">*(see notes)</a> , <br /> or select Defined Here and input URL below</small>",
            	"id" => "header",
				"old_id" => "techheader",
            	"type" => "select",
            	"std" => "Grunge",
				"java" => "onchange=\"header(this.form)\"",
            	"options" => array("Rotate", "Random_Lines_1", "Random_Lines_2", "Landscape", "Technology", "Grunge", "Defined Here","none")),
				
		array(	"name" => "Header Image Alignment<br /><small> Align header to the Left, Right, or Center the image in the Header Container</small>",
            	"id" => "header_align",
				"old_id" => "unused before 1.8.4",
            	"type" => "select",
            	"std" => "Center",
            	"options" => array("Left","Right","Center")),

    	array(	"name" => "Header Container Height <br /><small>Adjust the size of the container holding the header image<a href=\"javascript:tabchange(6)\">*(see notes)</a> <br />Default Height: 200px</small>",
            	"id" => "header_height",
				"old_id" => "unused before 1.8.4",
            	"std" => "200",
				"text" => "px",
				"size" => "5",
            	"type" => "text"),				
				
    	array(	"name" => "Header Image URL <br /><small> Needs to be full path the header image<br /> Example: <em>http://www.example.com/header.jpg</em> <a href=\"javascript:tabchange(6)\">*(see notes)</a> <br />Max Height: 200px</small>",
            	"id" => "header_image_url",
				"old_id" => "tech_header_image_url",
            	"std" => "http://",
				"size" => "50",
            	"last" => "</table><p><a href=\"javascript:tabchange(6)\">Back to Header Image</a></p></div>",
            	"type" => "text")
);
?>